version: "3.7"

x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "6100"
    configs:
      - source: loki_config
        target: /mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    logging: *loki-logging
    deploy:
      # replicas: 2
      placement:
        constraints:
          - node.labels.logsystem==true

  promtail:
    image: grafana/promtail:2.4.2
    configs:
      - source: promtail_config
        target: /mnt/config/promtail-config.yaml
    volumes:
      - /var/lib/docker/containers:/host/containers
    command: -config.file /mnt/config/promtail-config.yaml
    logging: *loki-logging
    deploy:
      mode: global
      # replicas: 2

  grafana:
    image: grafana/grafana:latest
    ports:
      - "7000:3000"
    configs:
      - source: grafana_config
        target: /etc/grafana/provisioning/datasources/loki-datasource.yml
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: testloki
    logging: *loki-logging
    deploy:
      placement:
        constraints:
          - node.labels.logsystem==true

  demo-app:
    image: ealen/echo-server
    ports:
      - "3001:80"
    logging: *loki-logging
    deploy:
      placement:
        constraints:
          - node.labels.bidder==true

  chi-app:
    image: 127.0.0.1:5000/chi
    build:
      context: ./chirouter
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5555:5555"
    logging: *loki-logging
    deploy:
      placement:
        constraints:
          - node.labels.bidder==true

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server ~ --address ':9000' --console-address ':9001'
    deploy:
      placement:
        constraints:
          - node.labels.logsystem==true

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/loki;
      /usr/bin/mc mb myminio/loki;
      /usr/bin/mc policy set private myminio/loki;
      exit 0;
      "
    deploy:
      placement:
        constraints:
          - node.labels.logsystem==true

configs:
  promtail_config:
    file: ./config/loki/promtail-config.yaml
  loki_config:
    file: ./config/loki/loki-config.yaml
  grafana_config:
    file: ./config/grafana/provisioning/datasources/loki-datasource.yml

volumes:
  grafana-data:

networks:
  loki:
