version: "3.7"

x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100"
    volumes:
      - ./config/loki/loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki
    logging: *loki-logging
    deploy:
      placement:
        constraints:
          - node.labels.logsystem == true

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - ./config/loki/promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/lib/docker/containers:/host/containers
    command: -config.file /mnt/config/promtail-config.yaml
    networks:
      - loki
    logging: *loki-logging
    deploy:
      placement:
        constraints:
          - node.labels.bidder == true

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - loki
    environment:
      GF_SECURITY_ADMIN_PASSWORD: testloki
    logging: *loki-logging
    deploy:
      placement:
        constraints:
          - node.labels.logsystem == true

  demo-app:
    image: ealen/echo-server
    ports:
      - "3001:80"
    networks:
      - loki
    logging: *loki-logging
    deploy:
      placement:
        constraints:
          - node.labels.bidder == true

volumes:
  grafana-data:

networks:
  loki:
