auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  wal:
    enabled: true
    dir: /tmp/wal
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
      heartbeat_timeout: 10m
    final_sleep: 20s
  chunk_idle_period: 1h # How long chunks should sit in-memory with no updates before being flushed
  chunk_retain_period: 20s # How long chunks should be retained in-memory after they've been flushed.
  chunk_target_size: 5572864 # 5mb
  max_chunk_age: 1h
  max_transfer_retries: 0

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
    - loki:7946
  max_join_backoff: 5m
  max_join_retries: 10
  min_join_backoff: 1s

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    resync_interval: 5s
    shared_store: s3
  aws:
    s3: http://minioadmin:minioadmin@minio.:9000/loki
    s3forcepathstyle: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: aws
