auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  # wal:
  #   enabled: true
  #   dir: /tmp/wal
  lifecycler:
    # address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 3
    final_sleep: 60s
  chunk_idle_period: 5m # Any chunk not receiving new logs in this time will be flushed 10m
  chunk_retain_period: 30s # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_chunk_age: 5m # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1000 # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  max_transfer_retries: 0 # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-07-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    # s3: s3://qnucnvyfijwqk2nrpwv6:b7pcmre8vipnbewovqez7fj34gxah27tbaxmmnj0qqa@nyc3.digitaloceanspaces.com/elite-server-mon
    s3: http://minio321:minio456@localhost:9000/log-bucket
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    shared_store: s3
    cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
  filesystem:
    directory: /tmp/loki/chunks

# ruler:
#   storage:
#     s3:
#       bucketnames: elite-server-mon

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: s3
  # shared_store: filesystem
  compaction_interval: 5m

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 0s
